# Standard Python CI workflows for the project.
#
# Based on the "Python workflow" provided by GitHub.

name: CI (python)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with tox
      run: |
        tox -c py
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v4
    #- name: Set up Python environment
    #  uses: actions/setup-python@v3
    #  with:
    #    python-version: "3.11"
    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install tox
    #- name: Test with tox
    #  run: |
    #    tox -c py
