# Standard Shell CI workflows for the project.

name: CI (python)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y shellcheck
    - name: Test with tox
      run: |
        shellcheck -x shell
